### ISSUE TITLE
AttributeError when creating an oi.CtlProgram instance

### ISSUE THREAD

**Issue by arcimboldo** [walkr/oi#4]
I was testing the example on the web page, but when I try to instantiate a CtlProgram class I get:

```
Traceback (most recent call last):
  File "programctl.py", line 5, in <module>
    ctl = oi.CtlProgram('ctl program', address='ipc:///tmp/program.sock')
  File "/home/antonio/git/others/oi/oi/core.py", line 257, in __init__
    self.client = ClientWrapper(address, timeout) if address else None
  File "/home/antonio/git/others/oi/oi/core.py", line 149, in __init__
    self.c = self.create_client(address, timeout)
  File "/home/antonio/git/others/oi/oi/core.py", line 163, in create_client
    return make(addr)
  File "/home/antonio/git/others/oi/oi/core.py", line 156, in make
    c.sock._set_recv_timeout(timeout)
AttributeError: 'Client' object has no attribute 'sock'
```

The issue is solved by just removing the call to `c.sock._set_recv_timeout(timeout)` in https://github.com/walkr/oi/blob/master/oi/core.py#L156

**Comment by walkr** [comment]
It was a bug caused by an update to dependent library (nanoservice).
Fixed!
